### ISSUE TITLE
Issues while setting a state in onChange!

### ISSUE THREAD

**Issue by mohdabbas** [dowjones/react-dropdown-tree-select#458] opened 2021-01-26 17:14 UTC
If I try to set a state on onChange, the state gets updated, but the value in the dropdown does not gets updated, it must be reselected, then it appears! Then if I select another option, again "root" is displayed, and I have to re-click the option. 
This is an awkward behaviour. How can we get the value from the dropdown? Is there anything I am missing? I need to post the selected value to the API from the state!

Here is the code!
```
const EditNote = ({editNoteData})=>{
  const[assignFolderId,setAssignFolderId] = useState();
  useEffect(()=>{
    if(editNoteData && editNoteData.folders){
      editNoteData.folders.unshift({id: "", name: "root", checked: false});
    }
  }, [editNoteData]);

//On Change Method
  const onChangeDropDown = (currentNode, selectedNodes) => {
    setAssignFolderId(currentNode.value);
  }

  return (
      <FoldersTree data={editNoteData.folders}  onChangeDropDown={onChangeDropDown} setAssignFolderId={setAssignFolderId} />
  )
}
```
FoldersTree
```
const FoldersTree = ({ data, onChangeDropDown, setAssignFolderId }) => {
  
useEffect(()=>{
  }, []);

return (
    <DropdownTreeSelect className="dropDownStyle"  texts={{ placeholder: ' ' }} data={data}  
    onChange={onChangeDropDown} 
    mode="radioSelect" />
)
}
export default FoldersTree;
```
Any help will be appreciated. Thanks

**Comment by mrchief** [comment] 2021-01-27 21:23
Duplicate of https://github.com/dowjones/react-dropdown-tree-select/issues/356

**Closed by mrchief** 2021-01-27 21:23 UTC
