### ISSUE TITLE
Toggle dropdown visibility on click remove tag

### ISSUE THREAD

**Issue by poltor** [dowjones/react-dropdown-tree-select#134] opened 2018-07-12 09:44 UTC
In this example - https://dowjones.github.io/react-dropdown-tree-select/#/story/basic-no-extra-styles
If you clicked on X tag, it's toggle dropdown visibility. But in other example all works correctly.

Thx!

**Comment by mrchief** [comment] 2018-07-13 00:28
Can you elaborate a bit more? It always toggles visibility when you click on X in all examples.

**Comment by poltor** [comment] 2018-07-13 07:55
In this example, the component behaves differently - https://dowjones.github.io/react-dropdown-tree-select/#/story/with-bootstrap-styles

How can I get the same behavior? That the dropdown did not change when deleting the tag - https://dowjones.github.io/react-dropdown-tree-select/#/story/with-bootstrap-styles

**Comment by mrchief** [comment] 2018-07-13 18:22
That example is using a CodeSandbox and the CodeSandbox is using an older version (v1.3.0) of the component.

This looks like a regression at this point but I'm not sure if changing this would upset others (who probably are used to the current effect). Let me think about it and publish a proper fix for this.

You can use that version in the interim if you're not using the features that were introduced after that: https://github.com/dowjones/react-dropdown-tree-select/releases?before=v1.3.0

**Comment by priyanshu92** [comment] 2018-07-31 16:05
@mrchief I am also facing this issue. Every removal of a tag changes the state of `showDropdown`. It is because of `!prevState.showDropdown` on [this](https://github.com/dowjones/react-dropdown-tree-select/blob/master/src/index.js#L84) line. I think this bug got introduced when you removed the dependency on `react-simple-dropdown`.

**Comment by mrchief** [comment] 2018-07-31 18:31
I've been pondering over this and I think it's best to mark it as a regression and revert to the old behavior. 

@priyanshu92 I don't think that line is the real cause. [`onTagRemove`](https://github.com/dowjones/react-dropdown-tree-select/blob/master/src/index.js#L121) should not trigger the dropdown in the first place.

I'm bit swamped right now, so would love to have a PR on this. If not, I'll try my best to get to it as soon as I can.

**Comment by priyanshu92** [comment] 2018-07-31 18:47
> I don't think that line is the real cause

I tried removing that check and it is working fine. 

> onTagRemove should not trigger the dropdown in the first place.

So [`onTagRemove`](https://github.com/dowjones/react-dropdown-tree-select/blob/master/src/index.js#L121) itself is not doing anything. Removing the tag is also triggering `onClick` of the [`anchor`](https://github.com/dowjones/react-dropdown-tree-select/blob/master/src/index.js#L187) tag (which contains all the tags) which is causing this problem.

**Comment by mrchief** [comment] 2018-07-31 19:56
Yes, that click [used to be suppressed](https://github.com/dowjones/react-dropdown-tree-select/blame/ae17f39a092f1fd3c8d47a580f24052966263417/src/tag/index.js#L13) from being bubbled up.

**Comment by priyanshu92** [comment] 2018-08-01 07:28
Ahh Okay. Do you want me to add that back and create a PR?

**Closed** 2018-08-02 22:02 UTC
