### ISSUE TITLE
Warning: componentWillMount has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by ldeveber** [dowjones/react-dropdown-tree-select#386] opened 2020-06-24 21:03 UTC
**Describe the bug**
This warning appears in the console with React 16.13.1:
```
console.js?ec33:13 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: t
```

**To Reproduce**
https://codesandbox.io/s/react-dropdown-tree-select-dko2o?file=/index.js

**Expected behavior**
No warnings in the console, no unsafe lifecycle methods used.

**Screenshots**
<img width="1061" alt="Screen Shot 2020-06-24 at 4 57 08 PM" src="https://user-images.githubusercontent.com/4457752/85626927-c43ed800-b63b-11ea-8402-f5b64cf9a7d3.png">

**Environment (please complete the following information):**
 - Browser Chrome 83.0.4103.106
 - OS: macOS 10.15.5

**Additional context**
Let me know if more is needed?

**Comment by mrchief** [comment] 2020-06-24 22:10
Duplicate of #292

**Closed by mrchief** 2020-06-24 22:10 UTC
