### ISSUE TITLE
How to hide checkbox of parent nodes and do not allow to select

### ISSUE THREAD

**Issue by sowmiyaseshadriii** [dowjones/react-dropdown-tree-select#376] opened 2020-05-27 11:43 UTC
Thanks for awesome package,
I would like to know is there any way to disable parent nodes and should not allow to select.
is there any property to do, please help, thanks in advance

**Comment by mrchief** [comment] 2020-05-27 21:44
Duplicate of #369. Please follow that thread.

**Closed by mrchief** 2020-05-27 21:44 UTC
