### ISSUE TITLE
How to control the order of the selected items

### ISSUE THREAD

**Issue by luluwheelan** [dowjones/react-dropdown-tree-select#437] opened 2020-10-18 16:48 UTC
How can I change the order of the selected items? The default selected item order is the same as the data list order, I want to change the order as the user choosing item order: newly selected item will be appended to the selected list. Thanks for your help!

**Comment by mrchief** [comment] 2020-10-19 18:15
Duplicate of #435

**Closed by mrchief** 2020-10-19 18:15 UTC
