### ISSUE TITLE
How can I fix

### ISSUE THREAD

**Issue by habeebahmed** [dowjones/react-dropdown-tree-select#360] opened 2020-04-18 18:59 UTC
**Is your feature request related to a problem? Please describe.**
I keep getting this warning when I add react-dropdown-tree-select

**Describe the solution you'd like**
Do I need to upgrade anything?

<img width="1717" alt="Screenshot 2020-04-19 at 12 25 33 AM" src="https://user-images.githubusercontent.com/36078669/79668764-c9634f00-81d4-11ea-9bda-b24972bfe476.png">

**Comment by mrchief** [comment] 2020-04-20 00:47
Duplicate of #292

**Closed by mrchief** 2020-04-20 00:47 UTC
