### ISSUE TITLE
Deprecated lifecycle methods

### ISSUE THREAD

**Issue by KSkryabin** [dowjones/react-dropdown-tree-select#441] opened 2020-11-06 11:03 UTC
**Please help!**
 The library has deprecated lifecycle methods. It results in errors displaying in the browser console and errors displaying during unit testing. It's inconvenient and makes us worry about the ability to use this library in the future when we need to use React 17.x

We would be grateful for solving this issue!

![1](https://user-images.githubusercontent.com/72017473/98358818-f0c62000-202f-11eb-981f-16935e3d6b85.png)
![2](https://user-images.githubusercontent.com/72017473/98358831-f6236a80-202f-11eb-9c05-293413bfd4a6.png)

**Comment by mrchief** [comment] 2020-11-06 21:04
Duplicate of 292. PRs welcome! :)

**Closed by mrchief** 2020-11-06 21:04 UTC
